### ISSUE TITLE
Does is support updating Windows Services?

### ISSUE THREAD

**Issue by shrinidhi111** [cubiclesoft/service-manager#5]

**Comment by cubiclesoft** [comment]
Please provide clarification.  This tool is intended to be used as an intermediate layer between your program, written in whatever language you want to write it in, and the host OS.  It provides Service Manager-aware applications standardized installation, start, stop, restart, reload, and uninstall operations across all supported platforms.  It's not a generic service modification tool.  On Windows, 'sc.exe' already exists for generic service manipulation.
