### ISSUE TITLE
WaitFor not work...

### ISSUE THREAD

**Issue by despot84** [cubiclesoft/service-manager#6]
Не пойму как прописать зависимости, судя по коду, это не работает...

```
public function WaitFor($servicename, $display = false)
{
	$cmd = escapeshellarg($this->GetServiceManagerRealpath());
	$cmd .= " status " . escapeshellarg($servicename);
	return $this->RunCommand($cmd, $display);
}
```

**Comment by cubiclesoft** [comment]
Fixed.  I guess I've never called that function before.

**Comment by despot84** [comment]
> Fixed. I guess I've never called that function before.

How to use this feature?
In theory, the names of dependent services should be transferred to it
Also, it would be logical to specify dependent services when installing the service

**Comment by cubiclesoft** [comment]
The 'waitfor' feature simply waits for the PID file to exist and adds 2 seconds of sleep past that.  Service Manager doesn't write the PID file to disk until the Service Manager executable and target process are up and running.  The PID file option has to be specified during install for `waitfor` to work.  The existence of a PID file isn't 100% reliable though.

https://github.com/cubiclesoft/service-manager-src/blob/master/servicemanager.cpp#L1120

Registering service dependencies for Linux and Mac are relatively straightforward:  Edit `servicemanager_nix.systemd`, `servicemanager_nix.sysvinit`, and `servicemanager_mac.launchd` files for your application.  Then install.

I think I've had problems with `CreateServiceW()` registering dependencies for Windows in the past.  I know I've had problems removing NT services with dependencies.  Probably need to look at this again and add an option for setting up dependencies on Windows at creation time.

There is no consistent, cross-platform mechanism for service names.  So dependencies have to target each specific OS' service loading mechanism.  File-based service files make it relatively straightforward to do on *NIX systems and can already be done.  Windows is the oddball in that there currently isn't support in Service Manager for specifying dependencies.

**Comment by despot84** [comment]
I'm using Windows
Added dependency via service SC:
sc config %serviceName% depend=%dependencies%

**Comment by cubiclesoft** [comment]
Added dependency support to Service Manager.  Tested it and it seems to work as expected.
